import type { ToolEvent, ToolTrace } from './tool-events.js';

// Two fixture trajectories for the read-only customer-context workload. They differ in customer,
// in event order, and in exploratory noise so the compiler has to infer the dataflow instead of
// replaying a recorded sequence. `parentSpanId` is deliberately misleading in trace A: span
// lineage is observability, not data dependency. Token and LLM counts are fixtures, not benchmarks.
const A = '11111111-1111-4111-8111-111111111111';
const B = '22222222-2222-4222-8222-222222222222';
const eventId = (trace: string, n: number) =>
  `${trace.slice(0, 8)}-0000-4000-8000-${String(n).padStart(12, '0')}`;

const base = { policyVersion: 'read-policy-v1', writes: [] as ToolEvent['writes'] };
const context = (customerId: string) => ({
  customerId,
  tenantId: 'local-demo' as const,
  snapshot: 'fixtures-v1' as const,
});

export const sampleToolTraceA: ToolTrace = {
  traceId: A,
  taskKind: 'customer_context',
  task: 'Pull the account context for customer C-101 before reviewing the delayed order.',
  agentModel: 'recorded-demo-agent',
  tenantId: 'local-demo',
  snapshot: 'fixtures-v1',
  policyVersion: 'read-policy-v1',
  taskInput: { customerId: 'C-101' },
  status: 'success',
  llmInvocations: 7,
  agentTokens: 9120,
  durationMs: 41200,
  finalEventId: eventId(A, 5),
  events: [
    {
      ...base,
      eventId: eventId(A, 1),
      traceId: A,
      startMs: 0,
      endMs: 1400,
      adapterId: 'legacy_crm',
      adapterVersion: '0',
      operation: 'legacy_crm.search',
      args: { query: { source: 'literal', value: 'C-101 account overview' } },
      status: 'failed',
      errorClass: 'no_exportable_rows',
      effect: 'read',
      reads: [{ system: 'legacy_crm', kind: 'search', key: 'C-101' }],
      credentialScopeIds: ['crm:read'],
    },
    {
      ...base,
      eventId: eventId(A, 2),
      traceId: A,
      parentSpanId: eventId(A, 1),
      startMs: 1400,
      endMs: 1720,
      adapterId: 'crm',
      adapterVersion: '1',
      operation: 'crm.getCustomer',
      args: { customerId: { source: 'task_input', key: 'customerId', value: 'C-101' } },
      result: { schemaId: 'customer.v1', projection: { ...context('C-101'), eligible: true } },
      status: 'success',
      effect: 'read',
      reads: [{ system: 'crm', kind: 'customer', key: 'C-101', observedVersion: '1' }],
      credentialScopeIds: ['crm:read'],
    },
    {
      ...base,
      eventId: eventId(A, 3),
      traceId: A,
      parentSpanId: eventId(A, 1),
      startMs: 1720,
      endMs: 2150,
      adapterId: 'orders',
      adapterVersion: '1',
      operation: 'orders.list',
      args: {
        customerId: {
          source: 'event_output',
          ref: { producerEventId: eventId(A, 2), outputPath: 'customerId' },
          value: 'C-101',
        },
      },
      result: {
        schemaId: 'orders.v1',
        projection: { ...context('C-101'), orders: [{ id: 'O-101', daysLate: 8 }] },
      },
      status: 'success',
      effect: 'read',
      reads: [{ system: 'orders', kind: 'order_list', key: 'C-101', observedVersion: '1' }],
      credentialScopeIds: ['orders:read'],
    },
    {
      ...base,
      eventId: eventId(A, 4),
      traceId: A,
      parentSpanId: eventId(A, 3),
      startMs: 2150,
      endMs: 2400,
      adapterId: 'crm',
      adapterVersion: '1',
      operation: 'crm.getCustomer',
      args: { customerId: { source: 'task_input', key: 'customerId', value: 'C-101' } },
      result: { schemaId: 'customer.v1', projection: { ...context('C-101'), eligible: true } },
      status: 'success',
      effect: 'read',
      reads: [{ system: 'crm', kind: 'customer', key: 'C-101', observedVersion: '1' }],
      credentialScopeIds: ['crm:read'],
    },
    {
      ...base,
      eventId: eventId(A, 5),
      traceId: A,
      parentSpanId: eventId(A, 4),
      startMs: 2400,
      endMs: 2810,
      adapterId: 'payments',
      adapterVersion: '1',
      operation: 'payments.refundHistory',
      args: {
        customerId: {
          source: 'event_output',
          ref: { producerEventId: eventId(A, 2), outputPath: 'customerId' },
          value: 'C-101',
        },
      },
      result: { schemaId: 'refunds.v1', projection: { ...context('C-101'), refunds: [] } },
      status: 'success',
      effect: 'read',
      reads: [{ system: 'payments', kind: 'refund_history', key: 'C-101', observedVersion: '1' }],
      credentialScopeIds: ['payments:read'],
    },
  ],
  observableResult: {
    customerId: 'C-101',
    eligible: true,
    orderCount: 1,
    refundCount: 0,
    refundTotal: 0,
  },
};

export const sampleToolTraceB: ToolTrace = {
  traceId: B,
  taskKind: 'customer_context',
  task: 'Pull the account context for customer C-202 before answering the refund question.',
  agentModel: 'recorded-demo-agent',
  tenantId: 'local-demo',
  snapshot: 'fixtures-v1',
  policyVersion: 'read-policy-v1',
  taskInput: { customerId: 'C-202' },
  status: 'success',
  llmInvocations: 6,
  agentTokens: 7840,
  durationMs: 36800,
  finalEventId: eventId(B, 4),
  events: [
    {
      ...base,
      eventId: eventId(B, 1),
      traceId: B,
      startMs: 0,
      endMs: 360,
      adapterId: 'crm',
      adapterVersion: '1',
      operation: 'crm.getCustomer',
      args: { customerId: { source: 'task_input', key: 'customerId', value: 'C-202' } },
      result: { schemaId: 'customer.v1', projection: { ...context('C-202'), eligible: true } },
      status: 'success',
      effect: 'read',
      reads: [{ system: 'crm', kind: 'customer', key: 'C-202', observedVersion: '1' }],
      credentialScopeIds: ['crm:read'],
    },
    {
      ...base,
      eventId: eventId(B, 2),
      traceId: B,
      parentSpanId: eventId(B, 1),
      startMs: 360,
      endMs: 780,
      adapterId: 'payments',
      adapterVersion: '1',
      operation: 'payments.refundHistory',
      args: {
        customerId: {
          source: 'event_output',
          ref: { producerEventId: eventId(B, 1), outputPath: 'customerId' },
          value: 'C-202',
        },
      },
      result: {
        schemaId: 'refunds.v1',
        projection: { ...context('C-202'), refunds: [{ id: 'R-202', amount: 5 }] },
      },
      status: 'success',
      effect: 'read',
      reads: [{ system: 'payments', kind: 'refund_history', key: 'C-202', observedVersion: '1' }],
      credentialScopeIds: ['payments:read'],
    },
    {
      ...base,
      eventId: eventId(B, 3),
      traceId: B,
      parentSpanId: eventId(B, 2),
      startMs: 780,
      endMs: 790,
      adapterId: 'notes',
      adapterVersion: '1',
      operation: 'notes.draftSummary',
      args: { topic: { source: 'literal', value: 'refund summary' } },
      status: 'skipped',
      effect: 'pure',
      reads: [],
      credentialScopeIds: [],
    },
    {
      ...base,
      eventId: eventId(B, 4),
      traceId: B,
      parentSpanId: eventId(B, 3),
      startMs: 790,
      endMs: 1210,
      adapterId: 'orders',
      adapterVersion: '1',
      operation: 'orders.list',
      args: {
        customerId: {
          source: 'event_output',
          ref: { producerEventId: eventId(B, 1), outputPath: 'customerId' },
          value: 'C-202',
        },
      },
      result: {
        schemaId: 'orders.v1',
        projection: {
          ...context('C-202'),
          orders: [
            { id: 'O-202', daysLate: 3 },
            { id: 'O-extra', daysLate: 6 },
          ],
        },
      },
      status: 'success',
      effect: 'read',
      reads: [{ system: 'orders', kind: 'order_list', key: 'C-202', observedVersion: '1' }],
      credentialScopeIds: ['orders:read'],
    },
  ],
  observableResult: {
    customerId: 'C-202',
    eligible: true,
    orderCount: 2,
    refundCount: 1,
    refundTotal: 5,
  },
};

export const sampleToolTraces: ToolTrace[] = [sampleToolTraceA, sampleToolTraceB];
